# Generated by Django 5.1.3 on 2024-11-15 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
    ]
